### ISSUE TITLE
Failing Transaction

### ISSUE THREAD

**Issue by tonespy** [PaystackHQ/paystack-android#52]
# Problem/Motivation
I am trying to make a charge, and after setting up the card and validation(card validation and OTP), the App crashes base on an error from the sdk

## Proposed resolution
Check the TransactionManager. The error points here:

        if (transactionApiResponse.status.equalsIgnoreCase("1") ||transactionApiResponse.status.equalsIgnoreCase("success")){
            setProcessingOff();
            transactionCallback.onSuccess(transaction);
            return;
        }

## Repeatable
Always

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Create card
2. Create charge by attaching card
3. Add amount
4. Add email

## Expected Results:
Return transaction object

## Actual Results:
        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase java.lang.String)' on a null object reference
                at co.paystack.android.TransactionManager.handleApiResponse(TransactionManager.java:170)
                at co.paystack.android.TransactionManager.access$000(TransactionManager.java:37)
                at co.paystack.android.TransactionManager$AuthAsyncTask.onPostExecute(TransactionManager.java:361)
                at co.paystack.android.TransactionManager$AuthAsyncTask.onPostExecute(TransactionManager.java:339)
                at android.os.AsyncTask.finish(AsyncTask.java:651)
                at android.os.AsyncTask.access$500(AsyncTask.java:180)
                at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:158)
                at android.app.ActivityThread.main(ActivityThread.java:7225)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ibrahimlawal** [comment]
Very weird. Do you have a transaction reference for a transaction that failed so?

**Comment by tonespy** [comment]
I do not. You know I can only get a transaction / transaction reference if and only if it gets into either the error / response block.

**Comment by ibrahimlawal** [comment]
@tonespy this issue has been resolved. Thanks for the report.
